### PR TITLE
Resolved conflicts & added the active ad functionality

### PR DESCRIPTION
**Pull request by Ardethian**

### CODE REVIEW

**Comment by FreedomFighterSparrow** [comment]
I assume only the last pull request (#5) is relevant for review?

דרור שניר-חיים – מנהל פיתוח
dror.snir@kolzchut.org.il
[image: לאתר כל זכות] <http://www.kolzchut.org.il/>
בקרו אותנו ב-www.kolzchut.org.il <http://www.kolzchut.org.il/he/> וב-[image:
Facebook] <https://www.facebook.com/kolzchut/>  [image: בלוג]
<http://blog.kolzchut.org.il/>  [image: YouTube]
<https://www.youtube.com/user/KolZchut>

השימוש במידע המופיע באתר "כל זכות" אינו מהווה תחליף לקבלת
ייעוץ או טיפול משפטי מקצועי או אחר והסתמכות על האמור בו ועל
האמור בהתכתבויות עם צוות האתר היא באחריות המשתמש

**Comment by Ardethian** [comment]
Indeed, ignore the closed PR.

**Comment by FreedomFighterSparrow** [comment]
This should simply have 'type' => 'check' (or 'class' => 'HTMLCheckField',
which is equivalent). Then you can remove 'options', etc.

I missed that pull request - merged now - but I see Ad::isNotExpired() only
checks the end date, and has nothing to do with the active status - it
looks like you don't use it anywhere yet (?).

**Comment by Ardethian** [comment]
Thanks, I've added the checkbox. The [documentation ](https://www.mediawiki.org/wiki/Extension:Page_Forms/Input_types#checkbox)is a bit blurry about that.

Ad::isNotExpired() and Ad::active are 2 different things.
Ad::isNotExpired() checks whether the ad's visibility period has expired, and Ad::active is used to determine whether the user has disabled the ad completely. 

About it being used - I have a commit I haven't pushed yet, that takes Ad::active under consideration when fetching and saving the ad to the database.

**Comment by FreedomFighterSparrow** [comment]
Ah, that was the point - I didn't see it used anywhere yet. No problem,
I'll just wait :-)

**Comment by Ardethian** [comment]
Ah, I see I may have misguided you in https://github.com/kolzchut/mediawiki-extensions-Promoter/pull/5#issuecomment-388720321. Sorry about that, I guess I was a little confused myself. :)

**Comment by FreedomFighterSparrow** [comment]
Also, the documentation you referenced is for the PageForms extension - you needed the documention for [HTMLForm](https://www.mediawiki.org/wiki/HTMLForm).

**Comment by Ardethian** [comment]
> Also, the documentation you referenced is for the PageForms extension - you needed the documention for HTMLForm.

That explains it! Thanks!

**Comment by FreedomFighterSparrow** [comment]
So could you update the pull request with the correct element? Then I can
merge it .

**Comment by Ardethian** [comment]
Done

**Pull request merged**
